// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJzoXVGTjBSunFN6H-lhYBw773xtoDod4',
    appId: '1:511990390430:web:a1ceff613aa61b3d49658f',
    messagingSenderId: '511990390430',
    projectId: 'health-app-4a4c9',
    authDomain: 'health-app-4a4c9.firebaseapp.com',
    storageBucket: 'health-app-4a4c9.appspot.com',
    measurementId: 'G-05JZ594XKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACbAHPS8jmxcbFc5SgxawISwsJOg5wXkM',
    appId: '1:511990390430:android:3629ce363abeea2c49658f',
    messagingSenderId: '511990390430',
    projectId: 'health-app-4a4c9',
    storageBucket: 'health-app-4a4c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwwZCNpre4oCPG9K2cIZt46pj91hGt-HA',
    appId: '1:511990390430:ios:57104cd8d79a8d8849658f',
    messagingSenderId: '511990390430',
    projectId: 'health-app-4a4c9',
    storageBucket: 'health-app-4a4c9.appspot.com',
    iosBundleId: 'com.example.healthApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwwZCNpre4oCPG9K2cIZt46pj91hGt-HA',
    appId: '1:511990390430:ios:57104cd8d79a8d8849658f',
    messagingSenderId: '511990390430',
    projectId: 'health-app-4a4c9',
    storageBucket: 'health-app-4a4c9.appspot.com',
    iosBundleId: 'com.example.healthApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJzoXVGTjBSunFN6H-lhYBw773xtoDod4',
    appId: '1:511990390430:web:ad5e55bdb849b4da49658f',
    messagingSenderId: '511990390430',
    projectId: 'health-app-4a4c9',
    authDomain: 'health-app-4a4c9.firebaseapp.com',
    storageBucket: 'health-app-4a4c9.appspot.com',
    measurementId: 'G-Z0K79V8XS9',
  );
}
