/// Flutter icons HealthAppFonts
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HealthAppFonts
///      fonts:
///       - asset: fonts/HealthAppFonts.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HealthAppFonts {
  HealthAppFonts._();

  static const _kFontFam = 'HealthAppFonts';
  static const String? _kFontPkg = null;

  static const IconData patients = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
